development:
  adapter: mysql2
  database: ikashot
  host: localhost
  username: testuser
  password: password
  encoding: utf8

production:
  adapter: mysql2
  database: ikashot
  host: localhost
  username: testuser
  password: password
  encoding: utf8

